// file: /pages/index.js
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import TextInput from '@/components/TextInput';
import SubmitButton from '@/components/SubmitButton';
import ResponseDisplay from '@/components/ResponseDisplay';
import useApi from '@/hooks/useApi';
import { getUserPrompt } from "../prompts/promptUtils";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const { data, error, loading, fetchData } = useApi();

  const handleInputChange = (event) => {
    event.preventDefault();
    setInputValue(event.target.value);
  };
  const handleSubmit = async (event) => {
    event.preventDefault();
    const submitValue = getUserPrompt(inputValue);
    await fetchData("/api/openai", "POST", submitValue)
  };
  const handleKeyPress = (event) => {
    if (event.key === "Enter") {
      event.preventDefault();
    }
  };

  return (
    <div className="">
      <Head>
        <title>AI Film suggestion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <NavBar />
        <h1 className="title">MovieMuse</h1>
        <p className="title_paragraph">
          Enter your favorite movie, and we will suggest you good movies with
          similar story
        </p>
        <form onSubmit={handleSubmit}>
          <TextInput
            value={inputValue}
            onChange={handleInputChange}
            placeholder={"Enter the name of the movie"}
          />
          <ResponseDisplay
            data={data}
            error={error}
            loading={loading}
            movieName={inputValue}
            handleKeyPress={handleKeyPress}
          />
        </form>
      </main>
    </div>
  );
}
